name: Build Pipeline

# Runs on push and PRs to master
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  
  test:
    # if the commit message doesnt contain [skip-ci] then run this job 
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run Master unit tests
        run: docker build -f "master.Dockerfile" -t master/unit_tests --target test-env .  
        
      - name: Run Slave unit tests
        run: docker build -f "slave.Dockerfile" -t slave/unit_tests --target test-env . 
  
  build_and_deploy:
    # if the commit message doesnt contain [skip-ci] then run this job 
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Build Docker images and deploys them to DockerHub
    runs-on: ubuntu-latest
    
    steps:
      -  uses: actions/checkout@v2
         
      - name: Build Master image
        run: docker build --rm -f "master.Dockerfile" -t hypercube:master "."
    
      - name: Tag Master image for push
        run: docker tag hypercube:master projectpolygon/hypercube:master
        
      - name: Build Slave image
        run: docker build --rm -f "slave.Dockerfile" -t hypercube:slave "."
      
      - name: Tag Slave image for push
        run: docker tag hypercube:slave projectpolygon/hypercube:slave
    
      - name: Login to DockerHub
        run: docker login --username projectpolygon --password ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Push Master image to DockerHub
        run: docker push projectpolygon/hypercube:master
        
      - name: Push Slave image to DockerHub
        run: docker push projectpolygon/hypercube:slave
        
